In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from scipy import stats
import yaml
import statsmodels

In [2]:
PATH_OUT = Path.cwd().parents[1] / "results" / "ablation_relative.csv"
DIR_FIGURES = Path.cwd().parents[1] / "results" / "ablation_relative"
PATH_NAME_REPLACEMENTS_CONFIG = Path.cwd().parents[1] / "config" / "renaming.yml"
ESTIMATORS = [
    "bxt_bgso_kronrls",
    "bxt_bgso_logistic",
    "uniform_bxt_bgso",
    "bxt_bgso",
    "nrlmf_bxt_bgso_kronrls",
    "nrlmf_uniform_bxt_bgso",
    "nrlmf_bxt_bgso",
]
MAIN_ESTIMATOR = "bxt_bgso_kronrls"

In [3]:
PATHS_RESULTS = [
    Path.cwd().parents[1] / "results" / "results.csv",
    Path.cwd().parents[1] / "results" / "results_dali.csv",
    Path.cwd().parents[1] / "results" / "results_genoma.csv",
]

In [4]:
renaming = yaml.safe_load(PATH_NAME_REPLACEMENTS_CONFIG.read_text())
renaming["estimator"] = {
  # "nrlmf_bxt_bgso": "Oxytrees[Deep, YR]",
  # "bxt_bgso_logistic": "Oxytrees[Logistic]",
  # "bxt_bgso_kronrls": "Oxytrees",
  # "nrlmf_bxt_bgso_kronrls": "Oxytrees[RLS-Kron, YR]",
  # "dwnn_similarities_bxt_bgso": "Oxytrees[SWN]",
  # "nrlmf_dwnn_similarities_bxt_bgso": "Oxytrees[SWN, YR]",
  # "uniform_bxt_bgso": "Oxytrees[Mean]",
  # "nrlmf_uniform_bxt_bgso": "Oxytrees[Mean, YR]",

  # "nrlmf_bxt_bgso": "Oxytrees[+Deep, +YR]",
  # "bxt_bgso_logistic": "Oxytrees[+Logistic]",
  # "bxt_bgso_kronrls": "Oxytrees",
  # "nrlmf_bxt_bgso_kronrls": "Oxytrees[+YR]",
  # "uniform_bxt_bgso": "Oxytrees[-Leaf model]",
  # "nrlmf_uniform_bxt_bgso": "Oxytrees[-Leaf model, +YR]",

  "bxt_bgso_kronrls": "Oxytrees",
  "nrlmf_bxt_bgso": "[Deep, YR]",
  "bxt_bgso": "[Deep]",
  "bxt_bgso_logistic": "[Logistic]",
  "nrlmf_bxt_bgso_kronrls": "[YR]",
  "uniform_bxt_bgso": "[Mean]",
  "nrlmf_uniform_bxt_bgso": "[Mean, YR]",
}
sns.set_context("talk")
plt.rcParams.update(
    {
        "font.family": "Times New Roman",
        "figure.dpi": 300,
    }
)

In [5]:
results_df = pd.concat(
    [pd.read_csv(path) for path in PATHS_RESULTS],
)

In [6]:
results_df = results_df.loc[results_df["estimator"].isin(ESTIMATORS)]
results_df = results_df.set_index(["estimator", "dataset", "fold", "validation_setting"])
results_df = results_df.sort_values(by=["dataset", "fold", "validation_setting", "estimator", "start_time"])
results_df = results_df.loc[~results_df.index.duplicated(keep="last")]
results_df = results_df.drop(columns=["start_time"])
results_df = results_df.rename_axis(columns="metric").stack().rename("value")

In [7]:
display(results_df.loc[results_df.index.duplicated()])
results_df = results_df.loc[~results_df.index.duplicated(keep="last")]

Series([], Name: value, dtype: float64)

In [8]:
df = results_df.reset_index()

# Considering LT and TL together
df["masking_percent"] = df["validation_setting"].str.extract(r"_(\d+)$").astype(float).fillna(0)
df[["validation_setting", "metric"]] = df["metric"].str.rsplit("__", n=1, expand=True)

# The fold name will keep the original setting info
df["fold"] = df["validation_setting"] + "__" + df["fold"].astype(str)
df = df.replace({"validation_setting": {"LT": "LT+TL", "TL": "LT+TL"}})

# Renaming
df = df.replace(
    {
        "estimator": renaming["estimator"],
        "dataset": renaming["dataset"],
        "metric": renaming["metric"],
        "validation_setting": renaming["validation_setting"],
    }
)
df = df.set_index(df.columns.drop("value").tolist())

In [9]:
df = df.dropna()
df

                                                                           value
estimator  dataset  fold     validation_setting metric masking_percent
[Deep, YR] Davis    LL__0    Training           AUROC  0.0              0.989278
                                                AUPRC  0.0              0.911792
                    LL_M__0  Transductive       AUROC  0.0              0.952667
                                                AUPRC  0.0              0.318517
[Deep]     Davis    LT__0    Semi-inductive     AUROC  0.0              0.969686
...                                                                          ...
[Mean]     TE-Pirna LL__15   Training           AUPRC  75.0             0.424610
                    TL__15   Semi-inductive     AUROC  75.0             0.518757
                    TT__15   Inductive          AUPRC  75.0             0.049397
                    LL_M__15 Transductive       AUROC  75.0             0.684150
                                                AUPRC  75.0             0.165496

[58008 rows x 1 columns]

In [10]:
df.loc[df.index.duplicated()].sort_index()

                                                                           value
estimator dataset    fold    validation_setting metric masking_percent
Oxytrees  DPI-E      LL_M__0 Transductive       AUPRC  25.0             0.612819
                                                       25.0             0.500978
                                                       50.0             0.594467
                                                       50.0             0.454882
                                                       75.0             0.368778
...                                                                          ...
[YR]      miRTarBase TL__3   Semi-inductive     AUPRC  25.0             0.212925
                                                       50.0             0.215136
                                                AUROC  0.0              0.699781
                                                       25.0             0.690897
                                                       50.0             0.687694

[27540 rows x 1 columns]

In [11]:
normalized_df = df.loc[~df.index.duplicated(keep="last")]
normalized_df /= normalized_df.xs(renaming["estimator"][MAIN_ESTIMATOR], level="estimator")
normalized_df = normalized_df.dropna()

In [12]:
def format_p_value(p, alpha=0.05):
    if p > alpha:
        return f"$p \\approx {p:.2g}$"

    n_decimals = int(np.ceil(-np.log10(p)))
    pvalue_noexp = int(np.ceil(p * 10**n_decimals))

    if n_decimals == 1:
        return f"$p < 0.{pvalue_noexp:.0f}$"
    if pvalue_noexp == 10:
        short_pvalue_str = f"10^{{-{n_decimals - 1}}}"
    elif pvalue_noexp == 1:
        short_pvalue_str = f"10^{{-{n_decimals}}}"
    else:
        short_pvalue_str = f"{pvalue_noexp} \\cdot 10^{{-{n_decimals}}}"
    pvalue_eq = f"$p < {short_pvalue_str}$"
    return pvalue_eq

In [21]:
DIR_FIGURES.mkdir(parents=True, exist_ok=True)
alpha = 0.05
assert MAIN_ESTIMATOR == ESTIMATORS[0], "The main estimator must be the first in the order list"
order = list(map(renaming["estimator"].get, ESTIMATORS))

for name, group in normalized_df.groupby(
    ["validation_setting", "masking_percent", "metric"]
    # normalized_df.index.droplevel(["estimator", "dataset", "fold"]).names
):
    group = group.copy()
    group["value"] *= 100

    validation_setting, masking_percent, metric = name
    title = f"{validation_setting} | PMP: {masking_percent:2.0f}% | {metric}"

    fold_means = group.groupby(["dataset", "estimator"])["value"].mean()
    reference = fold_means.xs(renaming["estimator"][MAIN_ESTIMATOR], level="estimator")
    fold_means = fold_means.drop(renaming["estimator"][MAIN_ESTIMATOR], level="estimator")

    significance = (
        fold_means
        .groupby("estimator")
        .apply(lambda x: stats.wilcoxon(x.values, reference.values).pvalue)
    )
    display(significance)

    group = group.reset_index()

    display(group)
    plt.figure(figsize=(4, 4))
    plt.title(title)

    ax = sns.boxplot(
        data=group,
        x="estimator",
        y="value",
        legend=False,
        showmeans=False,
        showfliers=False,
        linecolor="black",
        linewidth=1.5,
        meanprops={
            "marker": "d",
            "markerfacecolor": "C1",
            "markeredgecolor": "w",
            "markersize": 5,
            "zorder": 100,
        },
        boxprops=dict(facecolor="C1"),
        order=order,
    )

    sns.stripplot(
        ax=ax,
        data=group,
        x="estimator",
        y="value",
        # hue=hue_col,
        # order=order,
        # palette=["k"] * mean_ranks.index.get_level_values(hue_col).nunique(),
        # color="black",
        marker="o",
        color="k",
        size=3,
        legend=False,
        order=order,
    )

    positions = {
        label.get_text(): tick
        for label, tick in zip(ax.get_xticklabels(), ax.get_xticks())
    }

    plt.xticks(rotation=45, ha="right", fontsize="large")
    ax.xaxis.set_tick_params(width=1.5)
    ax.yaxis.set_tick_params(width=1.5)

    # Add "(mean)" label to each x label
    # x_labels = [
    #     label.get_text() + f" ({means[label.get_text()]:.2g})"
    #     for label in ax.get_xticklabels()
    # ]
    # ax.set_xticklabels(x_labels)

    # plt.ylim(bottom=plt.ylim()[0] - 0.1 * (plt.ylim()[1] - plt.ylim()[0]))
    for axis in ["top", "bottom", "left", "right"]:
        ax.spines[axis].set_linewidth(1.5)

    means = group.groupby("estimator")["value"].mean().reindex(order)

    for xtick in ax.get_xticks():
        plt.annotate(
            # xtick,
            # plt.ylim()[0],
            # means.iloc[xtick],
            f"{means.iloc[xtick]:.0f}",
            # (xtick, plt.ylim()[0]),
            (xtick, means.iloc[xtick]),
            backgroundcolor="white",
            size="small",
            horizontalalignment="center",
            verticalalignment="center",
            bbox=dict(facecolor="white", edgecolor="k", pad=2, linewidth=1.5),
            xycoords="data",
            # xytext=(xtick, plt.ylim()[0]),
            # annotation_clip=False,
        )

    # Annotate p-values at y = 200
    if (significance < alpha).any():
        p_y_pos = ax.get_ylim()[1]
        new_y_top = p_y_pos + 0.1 * np.diff(ax.get_ylim())

        ax.set_ylim(top=new_y_top)

        for xtick, p in zip(ax.get_xticks()[1:], significance[order[1:]]):
            # p_text = format_p_value(p, alpha=alpha)

            if p < 0.0001:
                p_text = "***"
            elif p < 0.001:
                p_text = "**"
            elif  p < alpha:
                p_text = "*"
            else:
                continue

            plt.text(
                s = p_text,
                x = xtick,
                y = p_y_pos,
                # backgroundcolor="white",
                # size="small",
                size="large",
                horizontalalignment="center",
                verticalalignment="center",
                # xycoords="data",
            )

    plt.xticks(rotation=45, ha="right")
    plt.xlabel(None)
    plt.ylabel("Score relative to Oxytrees (%)")
    plt.savefig(
        DIR_FIGURES
        / f"{validation_setting}_{metric}_{masking_percent:02.0f}.pdf",
        bbox_inches="tight",
        pad_inches=0.1,
    )
    # plt.show()
    plt.clf()

estimator
[Deep, YR]    0.977966
[Deep]        0.678772
[Logistic]    0.072998
[Mean, YR]    0.021545
[Mean]        0.006714
[YR]          0.035339
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUPRC,0.0,90.433985
1,Oxytrees,Davis,TT__0,Inductive,AUPRC,0.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUPRC,0.0,79.442593
3,"[Deep, YR]",Davis,TT__0,Inductive,AUPRC,0.0,95.582923
4,[YR],Davis,TT__0,Inductive,AUPRC,0.0,101.340013
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUPRC,0.0,100.023438
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUPRC,0.0,68.397347
760,[YR],TE-Pirna,TT__15,Inductive,AUPRC,0.0,78.343868
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUPRC,0.0,55.809484
762,[Mean],TE-Pirna,TT__15,Inductive,AUPRC,0.0,56.179524

estimator
[Deep, YR]    0.678772
[Deep]        0.106995
[Logistic]    0.599487
[Mean, YR]    0.719727
[Mean]        0.207764
[YR]          0.846924
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUROC,0.0,94.092000
1,Oxytrees,Davis,TT__0,Inductive,AUROC,0.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUROC,0.0,96.736311
3,"[Deep, YR]",Davis,TT__0,Inductive,AUROC,0.0,97.292463
4,[YR],Davis,TT__0,Inductive,AUROC,0.0,100.392504
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUROC,0.0,103.674833
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUROC,0.0,97.438753
760,[YR],TE-Pirna,TT__15,Inductive,AUROC,0.0,93.986637
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUROC,0.0,91.982183
762,[Mean],TE-Pirna,TT__15,Inductive,AUROC,0.0,103.730512

estimator
[Deep, YR]    0.977966
[Deep]        0.120544
[Logistic]    0.072998
[Mean, YR]    0.030151
[Mean]        0.008362
[YR]          0.041260
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUPRC,25.0,85.896646
1,Oxytrees,Davis,TT__0,Inductive,AUPRC,25.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUPRC,25.0,82.995627
3,"[Deep, YR]",Davis,TT__0,Inductive,AUPRC,25.0,92.622841
4,[YR],Davis,TT__0,Inductive,AUPRC,25.0,95.693117
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUPRC,25.0,154.745524
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUPRC,25.0,94.234335
760,[YR],TE-Pirna,TT__15,Inductive,AUPRC,25.0,70.143914
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUPRC,25.0,55.539533
762,[Mean],TE-Pirna,TT__15,Inductive,AUPRC,25.0,65.850425

estimator
[Deep, YR]    0.524475
[Deep]        0.008362
[Logistic]    0.359131
[Mean, YR]    0.678772
[Mean]        0.063721
[YR]          0.638672
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUROC,25.0,92.627247
1,Oxytrees,Davis,TT__0,Inductive,AUROC,25.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUROC,25.0,96.787800
3,"[Deep, YR]",Davis,TT__0,Inductive,AUROC,25.0,97.443189
4,[YR],Davis,TT__0,Inductive,AUROC,25.0,99.580907
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUROC,25.0,106.792873
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUROC,25.0,99.443207
760,[YR],TE-Pirna,TT__15,Inductive,AUROC,25.0,86.915367
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUROC,25.0,92.817372
762,[Mean],TE-Pirna,TT__15,Inductive,AUROC,25.0,104.844098

estimator
[Deep, YR]    0.890381
[Deep]        0.018066
[Logistic]    0.047913
[Mean, YR]    0.047913
[Mean]        0.006714
[YR]          0.252380
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUPRC,50.0,83.720036
1,Oxytrees,Davis,TT__0,Inductive,AUPRC,50.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUPRC,50.0,80.565322
3,"[Deep, YR]",Davis,TT__0,Inductive,AUPRC,50.0,86.898379
4,[YR],Davis,TT__0,Inductive,AUPRC,50.0,89.516344
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUPRC,50.0,94.182211
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUPRC,50.0,99.746544
760,[YR],TE-Pirna,TT__15,Inductive,AUPRC,50.0,110.872961
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUPRC,50.0,80.645164
762,[Mean],TE-Pirna,TT__15,Inductive,AUPRC,50.0,82.125993

estimator
[Deep, YR]    0.421204
[Deep]        0.012451
[Logistic]    0.488708
[Mean, YR]    0.561401
[Mean]        0.094604
[YR]          0.890381
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUROC,50.0,92.672710
1,Oxytrees,Davis,TT__0,Inductive,AUROC,50.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUROC,50.0,97.013945
3,"[Deep, YR]",Davis,TT__0,Inductive,AUROC,50.0,99.608341
4,[YR],Davis,TT__0,Inductive,AUROC,50.0,99.807369
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUROC,50.0,108.348031
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUROC,50.0,88.653733
760,[YR],TE-Pirna,TT__15,Inductive,AUROC,50.0,78.835979
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUROC,50.0,83.774250
762,[Mean],TE-Pirna,TT__15,Inductive,AUROC,50.0,107.524985

estimator
[Deep, YR]    0.488708
[Deep]        0.001160
[Logistic]    0.012451
[Mean, YR]    0.151428
[Mean]        0.008362
[YR]          0.454285
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUPRC,75.0,76.493964
1,Oxytrees,Davis,TT__0,Inductive,AUPRC,75.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUPRC,75.0,85.183858
3,"[Deep, YR]",Davis,TT__0,Inductive,AUPRC,75.0,83.655698
4,[YR],Davis,TT__0,Inductive,AUPRC,75.0,82.337229
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUPRC,75.0,139.137189
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUPRC,75.0,141.520293
760,[YR],TE-Pirna,TT__15,Inductive,AUPRC,75.0,210.394248
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUPRC,75.0,212.356475
762,[Mean],TE-Pirna,TT__15,Inductive,AUPRC,75.0,79.594336

estimator
[Deep, YR]    0.977966
[Deep]        0.072998
[Logistic]    0.599487
[Mean, YR]    0.454285
[Mean]        0.207764
[YR]          0.846924
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,TT__0,Inductive,AUROC,75.0,93.466400
1,Oxytrees,Davis,TT__0,Inductive,AUROC,75.0,100.000000
2,[Logistic],Davis,TT__0,Inductive,AUROC,75.0,96.524827
3,"[Deep, YR]",Davis,TT__0,Inductive,AUROC,75.0,99.497307
4,[YR],Davis,TT__0,Inductive,AUROC,75.0,100.874159
...,...,...,...,...,...,...,...
758,[Logistic],TE-Pirna,TT__15,Inductive,AUROC,75.0,95.980445
759,"[Deep, YR]",TE-Pirna,TT__15,Inductive,AUROC,75.0,111.678436
760,[YR],TE-Pirna,TT__15,Inductive,AUROC,75.0,94.785443
761,"[Mean, YR]",TE-Pirna,TT__15,Inductive,AUROC,75.0,94.296578
762,[Mean],TE-Pirna,TT__15,Inductive,AUROC,75.0,96.740902

estimator
[Deep, YR]    0.599487
[Deep]        0.934082
[Logistic]    0.000122
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.000305
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUPRC,0.0,96.921186
1,[Deep],Davis,TL__0,Semi-inductive,AUPRC,0.0,84.949648
2,Oxytrees,Davis,LT__0,Semi-inductive,AUPRC,0.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUPRC,0.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUPRC,0.0,92.762120
...,...,...,...,...,...,...,...
1633,[YR],TE-Pirna,TL__15,Semi-inductive,AUPRC,0.0,102.469345
1634,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUPRC,0.0,30.626320
1635,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUPRC,0.0,69.395015
1636,[Mean],TE-Pirna,LT__15,Semi-inductive,AUPRC,0.0,32.823456
1637,[Mean],TE-Pirna,TL__15,Semi-inductive,AUPRC,0.0,75.189144

estimator
[Deep, YR]    0.678772
[Deep]        0.003357
[Logistic]    0.008362
[Mean, YR]    0.000183
[Mean]        0.000427
[YR]          0.072998
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUROC,0.0,97.344853
1,[Deep],Davis,TL__0,Semi-inductive,AUROC,0.0,90.053868
2,Oxytrees,Davis,LT__0,Semi-inductive,AUROC,0.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUROC,0.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUROC,0.0,97.534856
...,...,...,...,...,...,...,...
1633,[YR],TE-Pirna,TL__15,Semi-inductive,AUROC,0.0,91.611558
1634,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUROC,0.0,99.325220
1635,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUROC,0.0,87.164870
1636,[Mean],TE-Pirna,LT__15,Semi-inductive,AUROC,0.0,98.185179
1637,[Mean],TE-Pirna,TL__15,Semi-inductive,AUROC,0.0,90.966544

estimator
[Deep, YR]    0.561401
[Deep]        0.135376
[Logistic]    0.000122
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.008362
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUPRC,25.0,87.717565
1,[Deep],Davis,TL__0,Semi-inductive,AUPRC,25.0,90.769448
2,Oxytrees,Davis,LT__0,Semi-inductive,AUPRC,25.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUPRC,25.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUPRC,25.0,93.211627
...,...,...,...,...,...,...,...
1626,[YR],TE-Pirna,TL__15,Semi-inductive,AUPRC,25.0,82.384551
1627,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUPRC,25.0,36.791942
1628,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUPRC,25.0,66.565627
1629,[Mean],TE-Pirna,LT__15,Semi-inductive,AUPRC,25.0,39.969828
1630,[Mean],TE-Pirna,TL__15,Semi-inductive,AUPRC,25.0,76.404844

estimator
[Deep, YR]    0.524475
[Deep]        0.000427
[Logistic]    0.006714
[Mean, YR]    0.001160
[Mean]        0.000305
[YR]          0.638672
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUROC,25.0,94.446941
1,[Deep],Davis,TL__0,Semi-inductive,AUROC,25.0,90.086489
2,Oxytrees,Davis,LT__0,Semi-inductive,AUROC,25.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUROC,25.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUROC,25.0,97.344999
...,...,...,...,...,...,...,...
1626,[YR],TE-Pirna,TL__15,Semi-inductive,AUROC,25.0,88.464948
1627,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUROC,25.0,100.531915
1628,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUROC,25.0,86.140207
1629,[Mean],TE-Pirna,LT__15,Semi-inductive,AUROC,25.0,98.780264
1630,[Mean],TE-Pirna,TL__15,Semi-inductive,AUROC,25.0,95.472008

estimator
[Deep, YR]    0.389404
[Deep]        0.012451
[Logistic]    0.000183
[Mean, YR]    0.000061
[Mean]        0.000122
[YR]          0.561401
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUPRC,50.0,82.056831
1,[Deep],Davis,TL__0,Semi-inductive,AUPRC,50.0,83.522408
2,Oxytrees,Davis,LT__0,Semi-inductive,AUPRC,50.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUPRC,50.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUPRC,50.0,93.697201
...,...,...,...,...,...,...,...
1624,[YR],TE-Pirna,TL__15,Semi-inductive,AUPRC,50.0,105.984526
1625,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUPRC,50.0,44.868951
1626,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUPRC,50.0,88.478545
1627,[Mean],TE-Pirna,LT__15,Semi-inductive,AUPRC,50.0,44.156232
1628,[Mean],TE-Pirna,TL__15,Semi-inductive,AUPRC,50.0,83.673933

estimator
[Deep, YR]    0.252380
[Deep]        0.000183
[Logistic]    0.047913
[Mean, YR]    0.003357
[Mean]        0.002625
[YR]          0.890381
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUROC,50.0,91.467185
1,[Deep],Davis,TL__0,Semi-inductive,AUROC,50.0,89.041912
2,Oxytrees,Davis,LT__0,Semi-inductive,AUROC,50.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUROC,50.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUROC,50.0,98.115829
...,...,...,...,...,...,...,...
1624,[YR],TE-Pirna,TL__15,Semi-inductive,AUROC,50.0,87.675080
1625,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUROC,50.0,105.152048
1626,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUROC,50.0,89.205849
1627,[Mean],TE-Pirna,LT__15,Semi-inductive,AUROC,50.0,101.971062
1628,[Mean],TE-Pirna,TL__15,Semi-inductive,AUROC,50.0,95.212493

estimator
[Deep, YR]    0.359131
[Deep]        0.000427
[Logistic]    0.010254
[Mean, YR]    0.002014
[Mean]        0.000610
[YR]          0.761536
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUPRC,75.0,75.668286
1,[Deep],Davis,TL__0,Semi-inductive,AUPRC,75.0,81.560290
2,Oxytrees,Davis,LT__0,Semi-inductive,AUPRC,75.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUPRC,75.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUPRC,75.0,91.606530
...,...,...,...,...,...,...,...
1538,[YR],TE-Pirna,TL__15,Semi-inductive,AUPRC,75.0,87.622686
1539,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUPRC,75.0,97.684365
1540,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUPRC,75.0,98.947357
1541,[Mean],TE-Pirna,LT__15,Semi-inductive,AUPRC,75.0,84.512697
1542,[Mean],TE-Pirna,TL__15,Semi-inductive,AUPRC,75.0,105.056963

estimator
[Deep, YR]    0.761536
[Deep]        0.000061
[Logistic]    0.135376
[Mean, YR]    0.168823
[Mean]        0.083252
[YR]          0.890381
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LT__0,Semi-inductive,AUROC,75.0,89.343390
1,[Deep],Davis,TL__0,Semi-inductive,AUROC,75.0,84.836678
2,Oxytrees,Davis,LT__0,Semi-inductive,AUROC,75.0,100.000000
3,Oxytrees,Davis,TL__0,Semi-inductive,AUROC,75.0,100.000000
4,[Logistic],Davis,LT__0,Semi-inductive,AUROC,75.0,99.041491
...,...,...,...,...,...,...,...
1538,[YR],TE-Pirna,TL__15,Semi-inductive,AUROC,75.0,81.109293
1539,"[Mean, YR]",TE-Pirna,LT__15,Semi-inductive,AUROC,75.0,111.015551
1540,"[Mean, YR]",TE-Pirna,TL__15,Semi-inductive,AUROC,75.0,84.155759
1541,[Mean],TE-Pirna,LT__15,Semi-inductive,AUROC,75.0,98.554822
1542,[Mean],TE-Pirna,TL__15,Semi-inductive,AUROC,75.0,92.895942

estimator
[Deep, YR]    0.005371
[Deep]        0.000061
[Logistic]    0.000061
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.000061
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUPRC,0.0,104.705971
1,Oxytrees,Davis,LL__0,Training,AUPRC,0.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUPRC,0.0,92.758233
3,"[Deep, YR]",Davis,LL__0,Training,AUPRC,0.0,94.304796
4,[YR],Davis,LL__0,Training,AUPRC,0.0,85.025817
...,...,...,...,...,...,...,...
814,[Logistic],TE-Pirna,LL__15,Training,AUPRC,0.0,88.933602
815,"[Deep, YR]",TE-Pirna,LL__15,Training,AUPRC,0.0,96.128361
816,[YR],TE-Pirna,LL__15,Training,AUPRC,0.0,86.314540
817,"[Mean, YR]",TE-Pirna,LL__15,Training,AUPRC,0.0,46.872867
818,[Mean],TE-Pirna,LL__15,Training,AUPRC,0.0,66.953889

estimator
[Deep, YR]    0.000183
[Deep]        0.000061
[Logistic]    0.000061
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.000061
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUROC,0.0,100.134345
1,Oxytrees,Davis,LL__0,Training,AUROC,0.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUROC,0.0,99.639385
3,"[Deep, YR]",Davis,LL__0,Training,AUROC,0.0,99.543289
4,[YR],Davis,LL__0,Training,AUROC,0.0,98.986380
...,...,...,...,...,...,...,...
814,[Logistic],TE-Pirna,LL__15,Training,AUROC,0.0,99.534131
815,"[Deep, YR]",TE-Pirna,LL__15,Training,AUROC,0.0,99.905450
816,[YR],TE-Pirna,LL__15,Training,AUROC,0.0,99.573926
817,"[Mean, YR]",TE-Pirna,LL__15,Training,AUROC,0.0,96.040860
818,[Mean],TE-Pirna,LL__15,Training,AUROC,0.0,98.576361

estimator
[Deep, YR]    0.094604
[Deep]        0.000854
[Logistic]    0.000061
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.000122
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUPRC,25.0,94.238396
1,Oxytrees,Davis,LL__0,Training,AUPRC,25.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUPRC,25.0,91.656183
3,"[Deep, YR]",Davis,LL__0,Training,AUPRC,25.0,92.708061
4,[YR],Davis,LL__0,Training,AUPRC,25.0,85.694369
...,...,...,...,...,...,...,...
812,[Logistic],TE-Pirna,LL__15,Training,AUPRC,25.0,89.690264
813,"[Deep, YR]",TE-Pirna,LL__15,Training,AUPRC,25.0,79.310943
814,[YR],TE-Pirna,LL__15,Training,AUPRC,25.0,71.061880
815,"[Mean, YR]",TE-Pirna,LL__15,Training,AUPRC,25.0,43.817745
816,[Mean],TE-Pirna,LL__15,Training,AUPRC,25.0,72.602623

estimator
[Deep, YR]    1.000000
[Deep]        0.000061
[Logistic]    0.000610
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.012451
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUROC,25.0,93.489946
1,Oxytrees,Davis,LL__0,Training,AUROC,25.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUROC,25.0,98.994327
3,"[Deep, YR]",Davis,LL__0,Training,AUROC,25.0,99.032408
4,[YR],Davis,LL__0,Training,AUROC,25.0,98.693576
...,...,...,...,...,...,...,...
812,[Logistic],TE-Pirna,LL__15,Training,AUROC,25.0,100.053757
813,"[Deep, YR]",TE-Pirna,LL__15,Training,AUROC,25.0,98.572887
814,[YR],TE-Pirna,LL__15,Training,AUROC,25.0,98.489372
815,"[Mean, YR]",TE-Pirna,LL__15,Training,AUROC,25.0,95.193252
816,[Mean],TE-Pirna,LL__15,Training,AUROC,25.0,98.793993

estimator
[Deep, YR]    0.168823
[Deep]        0.000061
[Logistic]    0.000061
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.002014
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUPRC,50.0,84.433772
1,Oxytrees,Davis,LL__0,Training,AUPRC,50.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUPRC,50.0,90.181791
3,"[Deep, YR]",Davis,LL__0,Training,AUPRC,50.0,85.298368
4,[YR],Davis,LL__0,Training,AUPRC,50.0,82.603285
...,...,...,...,...,...,...,...
811,[Logistic],TE-Pirna,LL__15,Training,AUPRC,50.0,89.884919
812,"[Deep, YR]",TE-Pirna,LL__15,Training,AUPRC,50.0,90.743686
813,[YR],TE-Pirna,LL__15,Training,AUPRC,50.0,84.386655
814,"[Mean, YR]",TE-Pirna,LL__15,Training,AUPRC,50.0,59.294696
815,[Mean],TE-Pirna,LL__15,Training,AUPRC,50.0,76.834315

C:\Users\u0170502\AppData\Local\Temp\ipykernel_49848\3479775869.py:30: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(4, 4))

estimator
[Deep, YR]    0.389404
[Deep]        0.000061
[Logistic]    0.030151
[Mean, YR]    0.000122
[Mean]        0.000854
[YR]          1.000000
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUROC,50.0,87.989955
1,Oxytrees,Davis,LL__0,Training,AUROC,50.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUROC,50.0,98.540993
3,"[Deep, YR]",Davis,LL__0,Training,AUROC,50.0,97.841864
4,[YR],Davis,LL__0,Training,AUROC,50.0,98.092937
...,...,...,...,...,...,...,...
811,[Logistic],TE-Pirna,LL__15,Training,AUROC,50.0,100.330418
812,"[Deep, YR]",TE-Pirna,LL__15,Training,AUROC,50.0,96.358428
813,[YR],TE-Pirna,LL__15,Training,AUROC,50.0,97.749532
814,"[Mean, YR]",TE-Pirna,LL__15,Training,AUROC,50.0,96.989955
815,[Mean],TE-Pirna,LL__15,Training,AUROC,50.0,99.030031

estimator
[Deep, YR]    0.276855
[Deep]        0.000061
[Logistic]    0.001160
[Mean, YR]    0.000061
[Mean]        0.000061
[YR]          0.063721
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUPRC,75.0,72.207659
1,Oxytrees,Davis,LL__0,Training,AUPRC,75.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUPRC,75.0,87.544885
3,"[Deep, YR]",Davis,LL__0,Training,AUPRC,75.0,76.435281
4,[YR],Davis,LL__0,Training,AUPRC,75.0,78.110323
...,...,...,...,...,...,...,...
776,[Logistic],TE-Pirna,LL__15,Training,AUPRC,75.0,94.050362
777,"[Deep, YR]",TE-Pirna,LL__15,Training,AUPRC,75.0,58.254136
778,[YR],TE-Pirna,LL__15,Training,AUPRC,75.0,61.311556
779,"[Mean, YR]",TE-Pirna,LL__15,Training,AUPRC,75.0,56.029119
780,[Mean],TE-Pirna,LL__15,Training,AUPRC,75.0,90.085720

estimator
[Deep, YR]    0.330261
[Deep]        0.000061
[Logistic]    0.934082
[Mean, YR]    0.002014
[Mean]        0.168823
[YR]          0.106995
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL__0,Training,AUROC,75.0,80.732353
1,Oxytrees,Davis,LL__0,Training,AUROC,75.0,100.000000
2,[Logistic],Davis,LL__0,Training,AUROC,75.0,99.685071
3,"[Deep, YR]",Davis,LL__0,Training,AUROC,75.0,97.577477
4,[YR],Davis,LL__0,Training,AUROC,75.0,97.956527
...,...,...,...,...,...,...,...
776,[Logistic],TE-Pirna,LL__15,Training,AUROC,75.0,99.857531
777,"[Deep, YR]",TE-Pirna,LL__15,Training,AUROC,75.0,95.950806
778,[YR],TE-Pirna,LL__15,Training,AUROC,75.0,97.284622
779,"[Mean, YR]",TE-Pirna,LL__15,Training,AUROC,75.0,96.215721
780,[Mean],TE-Pirna,LL__15,Training,AUROC,75.0,98.432073

estimator
[Deep, YR]    0.015076
[Deep]        0.000061
[Logistic]    0.001526
[Mean, YR]    0.012451
[Mean]        0.000061
[YR]          0.015076
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUPRC,25.0,64.967797
1,Oxytrees,Davis,LL_M__0,Transductive,AUPRC,25.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUPRC,25.0,88.921858
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUPRC,25.0,87.031552
4,[YR],Davis,LL_M__0,Transductive,AUPRC,25.0,86.286081
...,...,...,...,...,...,...,...
812,[Logistic],TE-Pirna,LL_M__15,Transductive,AUPRC,25.0,68.379791
813,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,25.0,23.128393
814,[YR],TE-Pirna,LL_M__15,Transductive,AUPRC,25.0,42.835203
815,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,25.0,24.814766
816,[Mean],TE-Pirna,LL_M__15,Transductive,AUPRC,25.0,34.366259

estimator
[Deep, YR]    0.015076
[Deep]        0.000061
[Logistic]    0.094604
[Mean, YR]    0.025574
[Mean]        0.000305
[YR]          0.001160
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUROC,25.0,73.083175
1,Oxytrees,Davis,LL_M__0,Transductive,AUROC,25.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUROC,25.0,96.905641
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUROC,25.0,97.770225
4,[YR],Davis,LL_M__0,Transductive,AUROC,25.0,98.173099
...,...,...,...,...,...,...,...
812,[Logistic],TE-Pirna,LL_M__15,Transductive,AUROC,25.0,101.509603
813,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,25.0,95.926889
814,[YR],TE-Pirna,LL_M__15,Transductive,AUROC,25.0,98.386001
815,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,25.0,98.316403
816,[Mean],TE-Pirna,LL_M__15,Transductive,AUROC,25.0,97.250899

estimator
[Deep, YR]    0.151428
[Deep]        0.000061
[Logistic]    0.005371
[Mean, YR]    0.018066
[Mean]        0.000305
[YR]          0.072998
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUPRC,50.0,63.664382
1,Oxytrees,Davis,LL_M__0,Transductive,AUPRC,50.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUPRC,50.0,88.208702
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUPRC,50.0,70.269809
4,[YR],Davis,LL_M__0,Transductive,AUPRC,50.0,76.132638
...,...,...,...,...,...,...,...
811,[Logistic],TE-Pirna,LL_M__15,Transductive,AUPRC,50.0,82.467316
812,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,50.0,52.166740
813,[YR],TE-Pirna,LL_M__15,Transductive,AUPRC,50.0,82.162890
814,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,50.0,58.464200
815,[Mean],TE-Pirna,LL_M__15,Transductive,AUPRC,50.0,62.950084

estimator
[Deep, YR]    0.025574
[Deep]        0.000061
[Logistic]    0.252380
[Mean, YR]    0.072998
[Mean]        0.004272
[YR]          0.001526
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUROC,50.0,75.204862
1,Oxytrees,Davis,LL_M__0,Transductive,AUROC,50.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUROC,50.0,97.265118
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUROC,50.0,96.316245
4,[YR],Davis,LL_M__0,Transductive,AUROC,50.0,97.233116
...,...,...,...,...,...,...,...
811,[Logistic],TE-Pirna,LL_M__15,Transductive,AUROC,50.0,101.043986
812,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,50.0,91.391926
813,[YR],TE-Pirna,LL_M__15,Transductive,AUROC,50.0,95.029553
814,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,50.0,95.166016
815,[Mean],TE-Pirna,LL_M__15,Transductive,AUROC,50.0,98.322254

estimator
[Deep, YR]    0.524475
[Deep]        0.000061
[Logistic]    0.030151
[Mean, YR]    0.021545
[Mean]        0.003357
[YR]          0.168823
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUPRC,75.0,57.986169
1,Oxytrees,Davis,LL_M__0,Transductive,AUPRC,75.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUPRC,75.0,82.530294
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUPRC,75.0,69.244409
4,[YR],Davis,LL_M__0,Transductive,AUPRC,75.0,77.585524
...,...,...,...,...,...,...,...
776,[Logistic],TE-Pirna,LL_M__15,Transductive,AUPRC,75.0,93.269305
777,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,75.0,35.635954
778,[YR],TE-Pirna,LL_M__15,Transductive,AUPRC,75.0,55.849236
779,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUPRC,75.0,62.157652
780,[Mean],TE-Pirna,LL_M__15,Transductive,AUPRC,75.0,78.367360

estimator
[Deep, YR]    0.106995
[Deep]        0.000061
[Logistic]    0.977966
[Mean, YR]    0.803955
[Mean]        0.330261
[YR]          0.008362
Name: value, dtype: float64

,estimator,dataset,fold,validation_setting,metric,masking_percent,value
0,[Deep],Davis,LL_M__0,Transductive,AUROC,75.0,73.482036
1,Oxytrees,Davis,LL_M__0,Transductive,AUROC,75.0,100.000000
2,[Logistic],Davis,LL_M__0,Transductive,AUROC,75.0,99.626047
3,"[Deep, YR]",Davis,LL_M__0,Transductive,AUROC,75.0,97.447833
4,[YR],Davis,LL_M__0,Transductive,AUROC,75.0,98.164146
...,...,...,...,...,...,...,...
776,[Logistic],TE-Pirna,LL_M__15,Transductive,AUROC,75.0,99.813273
777,"[Deep, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,75.0,94.277319
778,[YR],TE-Pirna,LL_M__15,Transductive,AUROC,75.0,96.468216
779,"[Mean, YR]",TE-Pirna,LL_M__15,Transductive,AUROC,75.0,95.781449
780,[Mean],TE-Pirna,LL_M__15,Transductive,AUROC,75.0,97.685381